"""initial collections schema

Revision ID: 740872ea0cc8
Revises: 
Create Date: 2026-07-30 15:47:17.920296
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # referenced by the rendered JSONB(astext_type=...)
from sqlalchemy.dialects import postgresql

revision: str = '740872ea0cc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('borrowers',
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('emi_amount_paise', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('dpd', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=40), nullable=False),
    sa.Column('outstanding_paise', sa.Integer(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('dnd_registered', sa.Boolean(), nullable=False),
    sa.Column('attempts_today', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('loan_id')
    )
    with op.batch_alter_table('borrowers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrowers_phone'), ['phone'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('use_case', sa.String(length=40), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dialer_mode', sa.String(length=20), nullable=False),
    sa.Column('max_attempts_per_day', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_text', 'source_language', 'target_language', name='uq_translation')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Enum('BROWSER', 'PSTN', name='channel'), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('disposition', sa.Enum('PTP', 'PAID', 'DISPUTE', 'WRONG_NUMBER', 'NO_ANSWER', 'CALLBACK', 'ESCALATED', 'REFUSED', 'INCOMPLETE', name='disposition'), nullable=False),
    sa.Column('languages_detected', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('script_language', sa.String(length=10), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recording_uri', sa.String(length=400), nullable=True),
    sa.Column('transcript_uri', sa.String(length=400), nullable=True),
    sa.Column('compliance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('latency_stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['borrowers.loan_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_disposition'), ['disposition'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index('ix_calls_loan_started', ['loan_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_started_at'), ['started_at'], unique=False)

    op.create_table('analytics_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_english', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('disposition_predicted', sa.String(length=30), nullable=True),
    sa.Column('intents', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('objections', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('compliance_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('diarized_turns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('compliance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('regulation', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_events_kind'), ['kind'], unique=False)

    op.create_table('crm_writebacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('system', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['borrowers.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_writebacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_writebacks_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_writebacks_loan_id'), ['loan_id'], unique=False)

    op.create_table('escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('queue', sa.String(length=40), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['borrowers.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalations_loan_id'), ['loan_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_stage'), ['stage'], unique=False)

    op.create_table('payment_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('provider_ref', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel_sent', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['borrowers.loan_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_ref')
    )
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_links_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_loan_id'), ['loan_id'], unique=False)

    op.create_table('promises_to_pay',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('captured_language', sa.String(length=10), nullable=True),
    sa.Column('honoured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['borrowers.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promises_to_pay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promises_to_pay_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promises_to_pay_loan_id'), ['loan_id'], unique=False)

    op.create_table('tool_invocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('arguments', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'DEAD_LETTERED', name='toolstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_invocations_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_invocations_name'), ['name'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('BOT', 'BORROWER', 'SYSTEM', name='speaker'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('barged_in', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'idx', name='uq_turn_call_idx')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_call_id'), ['call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_call_id'))

    op.drop_table('turns')
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_invocations_name'))
        batch_op.drop_index(batch_op.f('ix_tool_invocations_call_id'))

    op.drop_table('tool_invocations')
    with op.batch_alter_table('promises_to_pay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promises_to_pay_loan_id'))
        batch_op.drop_index(batch_op.f('ix_promises_to_pay_call_id'))

    op.drop_table('promises_to_pay')
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_links_loan_id'))
        batch_op.drop_index(batch_op.f('ix_payment_links_call_id'))

    op.drop_table('payment_links')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_stage'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_events_call_id'))

    op.drop_table('events')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_loan_id'))
        batch_op.drop_index(batch_op.f('ix_escalations_call_id'))

    op.drop_table('escalations')
    with op.batch_alter_table('crm_writebacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_writebacks_loan_id'))
        batch_op.drop_index(batch_op.f('ix_crm_writebacks_call_id'))

    op.drop_table('crm_writebacks')
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_events_kind'))
        batch_op.drop_index(batch_op.f('ix_compliance_events_call_id'))

    op.drop_table('compliance_events')
    op.drop_table('analytics_reports')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_started_at'))
        batch_op.drop_index('ix_calls_loan_started')
        batch_op.drop_index(batch_op.f('ix_calls_loan_id'))
        batch_op.drop_index(batch_op.f('ix_calls_disposition'))
        batch_op.drop_index(batch_op.f('ix_calls_campaign_id'))

    op.drop_table('calls')
    op.drop_table('translation_cache')
    op.drop_table('campaigns')
    with op.batch_alter_table('borrowers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowers_phone'))

    op.drop_table('borrowers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
